# Generated by Django 5.1.7 on 2025-03-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_project_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Сайт', 'Site'), ('Дискорд', 'Discord'), ('Гильдия', 'Guild'), ('Другое', 'Other')], default='Другое', max_length=100, verbose_name='Тип')),
                ('url', models.URLField(max_length=500, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
                'db_table': 'links',
            },
        ),
    ]
