# Generated by Django 5.1.7 on 2025-03-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_link_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Инфа'),
        ),
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.CharField(choices=[('Site', 'Сайт'), ('Discord', 'Дискорд'), ('Guild', 'Гильдия'), ('Other', 'Другое')], default='Other', max_length=100, verbose_name='Тип'),
        ),
    ]
