# Generated by Django 5.1.7 on 2025-03-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_project_info_alter_link_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.CharField(choices=[('Site', 'Сайт'), ('Discord', 'Дискорд'), ('Guild', 'Гильдия'), ('Guide', 'Гайд'), ('Other', 'Другое')], default='Site', max_length=100, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[(1, 'Тир 1'), (2, 'Тир 2'), (3, 'Антифомо')], default=3, max_length=100, verbose_name='Приоритет'),
        ),
    ]
