# Generated by Django 5.1.7 on 2025-03-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_link_type_alter_project_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('Tier 1', 'Тир 1'), ('Tier 2', 'Тир 2'), ('Tier 3', 'Тир 3'), ('Antifomo', 'Антифомо')], default='Antifomo', max_length=100, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Active', 'Активный'), ('Finished', 'Завершен'), ('Abandoned', 'Забросил')], default='Active', max_length=100, verbose_name='Статус'),
        ),
    ]
